---


- name: Locale generate
  become: true
  command: locale-gen zh_TW.UTF-8

- name: Setting Default Locale
  become: true
  command: |
    echo 'LANG="zh_TW.UTF-8"' >> /etc/default/locale;
    export LANG=zh_TW.UTF-8;

- name: Oh-My-Zsh script download
  command: curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -o /tmp/omz.sh

- name: Oh-My-Zsh installation
  become: true
  command: sh /tmp/omz.sh
  tags: terminal

- name: Oh-My-Zsh Config File Copy
  copy:
    src: configs/.zshrc
    dest: ~/.zshrc

- name: Oh-My-Zsh Custom Theme Copy
  copy:
    src: configs/aweimeow.zsh-theme
    dest: ~/.oh-my-zsh/themes/

- name: Terminal plugin clone
  git:
    repo: "{{ item.value.url }}"
    dest: "{{ item.value.dest }}"
  with_dict: "{{ terminal_plugin }}"
  tags: terminal

- name: Terminal plugin install
  command: "{{ item.value.setup }}"
  with_dict: "{{ terminal_plugin }}"
  tags: terminal

- name: Change Default Shell
  become: true
  command: "chsh -s /bin/zsh {{ ansible_ssh_user }}"
